package com.model;

/**
 * TRuchang generated by MyEclipse Persistence Tools
 */

public class TRuchang implements java.io.Serializable
{

	private Integer id;
	private String rushijian;
	private String chexing;
	private String chehao;
	
	private String kahao;
	private String beizhu;
	private String chushijian;
	private Integer feiyong;

	public TRuchang()
	{
	}


	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}


	public String getRushijian()
	{
		return rushijian;
	}


	public void setRushijian(String rushijian)
	{
		this.rushijian = rushijian;
	}


	public String getChexing()
	{
		return this.chexing;
	}

	public void setChexing(String chexing)
	{
		this.chexing = chexing;
	}

	public String getChehao()
	{
		return chehao;
	}


	public void setChehao(String chehao)
	{
		this.chehao = chehao;
	}


	public String getKahao()
	{
		return this.kahao;
	}

	public void setKahao(String kahao)
	{
		this.kahao = kahao;
	}

	public String getBeizhu()
	{
		return this.beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getChushijian()
	{
		return this.chushijian;
	}

	public void setChushijian(String chushijian)
	{
		this.chushijian = chushijian;
	}

	public Integer getFeiyong()
	{
		return this.feiyong;
	}

	public void setFeiyong(Integer feiyong)
	{
		this.feiyong = feiyong;
	}

}